version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      # Variabel-variabel ini akan diisi di dashboard Railway
      GENERIC_TIMEZONE: ''
      N8N_HOST: ''
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      N8N_BASIC_AUTH_ACTIVE: ''
      N8N_BASIC_AUTH_USER: ''
      N8N_BASIC_AUTH_PASSWORD: ''
